name: matrix
on:
  # schedule:
  #   - cron: '0 5 * * *' # every day at 5am UTC
  workflow_dispatch:

jobs:

  build:
    permissions:
      packages: write # to write to ghcr.io
      contents: write # to commit to the repo (examples)
    
    runs-on: "ubuntu-latest" # ${{ matrix.arch.runner }}
    strategy:
      fail-fast: false # let other jobs try to complete if one fails
      matrix: # @TODO: this is stupid, we should be able to use the repos.yaml directly; use a prepare job to generate the matrix from repos.yaml into a GHA output with JSON in it
        include:
          - { id: "kubernetes-sigs-cluster-api-operator" }
          - { id: "kubernetes-ingress-nginx" }
          - { id: "grafana" }
          - { id: "prometheus-community" }
    env:
      BASE_OCI_REF: "ghcr.io/${{ github.repository_owner }}/"
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    name: "${{ matrix.id }}"
    
    steps:

      - name: Checkout build repo
        uses: actions/checkout@v4

      - name: Docker Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }} # GitHub username or org
          password: ${{ secrets.GITHUB_TOKEN }}    # GitHub actions builtin token. repo has to have pkg access.

      - name: setup python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          #cache: 'pip' # caching pip dependencies -- not useful, we're using venv
      
      # Setup Helm
      - name: Setup latest Helm
        uses: azure/setup-helm@v4.0.0 # v4 only does not work?
        with:
          version: "latest"
          #token: ${{ secrets.GITHUB_TOKEN }} # is already in the job's ENV

      - name: install pip deps
        run: |
          python3 -m venv .venv
          .venv/bin/pip install -r requirements.txt

      - name: "Do it: ${{matrix.id}}"
        id: doit
        run: |
          git pull || true # install deps is slow; repo might have changed
          .venv/bin/python process --repo-id "${{ matrix.id }}"

      - name: Commit changes to the info directory
        run: |
          git config --global user.name "GHA workflow"
          git config --global user.email "workflow@github.com"
          git pull || true # repo might have changed since we started, avoid conflicts
          git add info || true
          git commit -m "Update info for ${{ matrix.id }}" || true
          git push || true


  #release:
  #  needs: [ build ] # depend on the previous jobs...
  #  if: "${{ !cancelled() }}" # ... but run even if (some of) them failed, but not if job was cancelled
  #  runs-on: ubuntu-latest
  #  steps:
  #    - name: List current dir
  #      run: |
  #        ls -lahtR
